#!/usr/bin/env python3
"""
Generate LaTeX examples of label lists for each factor pole.

For each factor facK and each pole (positive / negative):
    - positive pole: texts (label lists) ranked by descending facK
    - negative pole: texts ranked by ascending facK
    - take the top N examples per pole (default: 20)
    - skip any file where facK == 0

Each example shows:
    - filename (so you can trace back to the image / JSON)
    - factor score
    - the full label list, with primary factor labels in bold.

Requires:

- SAS output:
    sas/output_cl_st1_ph1_tatiana/cl_st1_ph1_tatiana_scores_only.tsv
      (must contain columns: filename, fac1, fac2, ...)

- Factor primary-label files:
    factors/f<n>_pos.txt
    factors/f<n>_neg.txt
  generated by factor_lists.py

- Label list files:
    corpus/03_label_types/<filename>.txt
  produced by label_types.py

- file_ids.txt (optional but used here):
    maps the IDs in the scores file (e.g. t000018)
    to actual label filenames (e.g. tweet_000018_000001.txt)

This script writes:

- Per-factor/pole LaTeX snippets under:
    examples/fK_pos/*.tex
    examples/fK_neg/*.tex

- A master LaTeX file:
    examples/examples.tex
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Set, Tuple

import pandas as pd

# =============================================================================
# CONFIGURATION
# =============================================================================

# Where label-list files live
LABEL_DIR = Path("corpus/03_label_types")

# Where factor primary-label files live
FACTOR_FOLDER = Path("factors")

# Where SAS scores_only output is
SCORES_FILE = Path(
    "sas/output_cl_st1_ph1_tatiana/cl_st1_ph1_tatiana_scores_only.tsv"
)

# Optional mapping from scores IDs (e.g. t000018) to label filenames
FILE_IDS_PATH = Path("file_ids.txt")

# Output directory for LaTeX examples
EXAMPLES_DIR = Path("examples")
EXAMPLES_DIR.mkdir(exist_ok=True)

# Number of examples per pole
TOP_N_PER_POLE = 40

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def load_primary_lemmas(pole_file: Path) -> Set[str]:
    """
    Load primary lemmas (labels) for a given factor pole from factors/f<n>_pos.txt or f<n>_neg.txt.

    Expects the first line to be a header like:
        variables loading on this pole = N

    Subsequent line(s) contain entries like:
        label1 (.85), label2 (.73), ...

    Returns a set of lemma strings: {"label1", "label2", ...}.
    """
    if not pole_file.exists():
        return set()

    lines = pole_file.read_text(encoding="utf-8").splitlines()
    if not lines:
        return set()

    # Skip header line
    body = " ".join(lines[1:])
    items = [item.strip() for item in body.split(",") if item.strip()]
    lemmas: Set[str] = set()

    # Match label possibly wrapped in parentheses before the score
    pattern = re.compile(r"\(?(?P<lem>[A-Za-z0-9_-]+)\s*\(")

    for item in items:
        m = pattern.match(item)
        if m:
            lemmas.add(m.group("lem"))

    return lemmas


def load_scores(scores_file: Path) -> pd.DataFrame:
    """
    Load scores_only TSV.

    Must contain:
      - 'filename'
      - 'fac1', 'fac2', ...
    """
    if not scores_file.exists():
        raise FileNotFoundError(f"Scores file not found: {scores_file}")

    df = pd.read_csv(scores_file, sep="\t")

    if "filename" not in df.columns:
        raise ValueError("Scores file must have a 'filename' column.")

    # Detect factor columns
    factor_cols = [c for c in df.columns if c.startswith("fac")]
    if not factor_cols:
        raise ValueError("Scores file has no 'fac*' columns.")

    return df


def extract_factor_columns(df: pd.DataFrame) -> List[str]:
    """Return the list of factor columns in the DataFrame, sorted by factor index."""
    factor_cols = [c for c in df.columns if c.startswith("fac")]
    # Sort by numeric suffix: fac1, fac2, ...
    factor_cols_sorted = sorted(
        factor_cols, key=lambda c: int(c.replace("fac", ""))  # type: ignore[arg-type]
    )
    return factor_cols_sorted


def load_label_list(label_file: Path) -> List[str]:
    """
    Load labels from a label-types .txt file (one label per non-empty line).
    Returns a list of labels as strings.
    """
    if not label_file.exists():
        return []

    labels: List[str] = []
    with label_file.open(encoding="utf-8") as f:
        for line in f:
            label = line.strip()
            if label:
                labels.append(label)
    return labels


def escape_latex(text: str) -> str:
    """
    Escape a minimal set of LaTeX special characters in a string.
    """
    replacements = {
        "\\": r"\textbackslash{}",
        "$": r"\$",
        "#": r"\#",
        "&": r"\&",
        "_": r"\_",
        "%": r"\%",
        "{": r"\{",
        "}": r"\}",
    }
    for ch, rep in replacements.items():
        text = text.replace(ch, rep)
    return text


def format_labels_for_latex(labels: List[str], primary_lemmas: Set[str]) -> str:
    """
    Format a sequence of labels for LaTeX, with labels in `primary_lemmas` in \\textbf{...}.

    Returns a single string, e.g.:
        \\textbf{science}, screenshot, health_care
    """
    formatted: List[str] = []
    for lab in labels:
        esc = escape_latex(lab)
        if lab in primary_lemmas:
            formatted.append(r"\textbf{" + esc + "}")
        else:
            formatted.append(esc)
    return ", ".join(formatted)


def load_id_mapping(path: Path) -> Dict[str, str]:
    """
    Load mapping from scores IDs to label filenames from file_ids.txt.

    Expected format (per non-empty, non-comment line):
        <scores_id> <label_filename>

    Fields are split on whitespace; only the first two fields are used.
    Lines starting with '#' are ignored.

    Returns a dict like: {"t000018": "tweet_000018_000001.txt", ...}
    """
    mapping: Dict[str, str] = {}

    if not path.exists():
        print(f"(info) file_ids mapping not found at {path}; proceeding without it.")
        return mapping

    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            src_id, dst_name = parts[0], parts[1]
            mapping[src_id] = dst_name

    print(f"(info) Loaded {len(mapping)} ID mappings from {path}")
    return mapping


# =============================================================================
# MAIN
# =============================================================================


def main() -> int:
    # Load scores
    scores_df = load_scores(SCORES_FILE)
    factor_cols = extract_factor_columns(scores_df)
    num_factors = len(factor_cols)
    print(f"Detected {num_factors} factors: {', '.join(factor_cols)}\n")

    # Ensure label directory exists
    if not LABEL_DIR.exists():
        print(f"Error: label directory not found: {LABEL_DIR}")
        return 1

    # Load optional ID mapping (scores filename -> label filename)
    id_mapping: Dict[str, str] = load_id_mapping(FILE_IDS_PATH)

    missing_label_files: Set[str] = set()

    # For building the master LaTeX file
    generated_sections: List[Tuple[int, str, List[Path]]] = []

    # Iterate over factors
    for fac_col in factor_cols:
        fac_num = int(fac_col.replace("fac", ""))

        for pole, ascending in (("pos", False), ("neg", True)):
            label = f"f{fac_num}_{pole}"
            print(
                f"→ {label}: selecting top {TOP_N_PER_POLE} examples "
                f"(col={fac_col}, ascending={ascending})"
            )

            primary_lemmas = load_primary_lemmas(FACTOR_FOLDER / f"{label}.txt")
            if not primary_lemmas:
                print(
                    f"  (warning) No primary lemmas found for {label}; continuing anyway."
                )

            # Sort by factor score
            sorted_df = scores_df.sort_values(by=fac_col, ascending=ascending)

            out_dir = EXAMPLES_DIR / label
            out_dir.mkdir(parents=True, exist_ok=True)

            tex_paths: List[Path] = []
            ex_id = 1

            for _, row in sorted_df.iterrows():
                score = row[fac_col]
                if score == 0 or pd.isna(score):
                    continue
                if ex_id > TOP_N_PER_POLE:
                    break

                # Filename as stored in the scores file (e.g. "t000018")
                raw_fname = str(row["filename"]).strip()

                # Map to actual label filename if available
                mapped_fname = id_mapping.get(raw_fname, raw_fname)

                # Construct label file path; if no extension, assume ".txt"
                label_file = LABEL_DIR / mapped_fname
                if label_file.suffix == "":
                    label_file = label_file.with_suffix(".txt")

                labels = load_label_list(label_file)
                if not labels:
                    # Record using the scores ID so you can see which ones failed
                    missing_label_files.add(raw_fname)
                    continue

                labels_tex = format_labels_for_latex(labels, primary_lemmas)

                # Encode filename for LaTeX display (show original scores ID)
                latex_fname = escape_latex(raw_fname)

                env_title = f"{pole.upper()} Dim {fac_num} – Score {score:.2f} – {latex_fname}"
                env_label = f"ex:{label}_{ex_id:03d}"

                out_file = out_dir / f"{label}_{ex_id:03d}.tex"
                tex_paths.append(out_file)

                with out_file.open("w", encoding="utf-8") as f:
                    f.write(
                        r"\begin{textsample}{"
                        + env_title
                        + r"}  \label{"
                        + env_label
                        + "}"
                        + "\n"
                    )
                    f.write(labels_tex + "\n\n")
                    f.write(r"% file (scores ID): " + latex_fname + "\n")
                    f.write(r"% label file: " + escape_latex(str(label_file)) + "\n")
                    f.write(r"\end{textsample}" + "\n")

                ex_id += 1

            print(f"  ✓ Wrote {ex_id-1} examples for {label}\n")
            generated_sections.append((fac_num, pole, tex_paths))

    # Missing label files report
    if missing_label_files:
        missing_path = EXAMPLES_DIR / "missing_label_files.txt"
        missing_path.write_text(
            "\n".join(sorted(missing_label_files)), encoding="utf-8"
        )
        print(f"⚠ Missing label files written to {missing_path}")

    # Build master LaTeX file
    top_header_path = EXAMPLES_DIR / "top_header"
    master = EXAMPLES_DIR / "examples.tex"

    if not top_header_path.exists():
        print(
            "\n⚠ top_header missing. Create examples/top_header before compiling LaTeX.\n"
        )
        preamble = r"% Provide a LaTeX preamble in examples/top_header"  # fallback
    else:
        preamble = top_header_path.read_text(encoding="utf-8")

    with master.open("w", encoding="utf-8") as out:
        out.write(preamble + "\n\n")
        out.write(r"\begin{document}" + "\n\n")
        out.write(r"\maketitle" + "\n\n")
        out.write(r"\tableofcontents" + "\n\n")

        # Write sections in factor/pole order
        for fac_num, pole, tex_files in generated_sections:
            if not tex_files:
                continue
            out.write(r"\section{" + f"{pole.upper()} Dim {fac_num}" + "}\n\n")
            for tex in sorted(tex_files):
                # Use path relative to examples/ for \input
                rel = tex.relative_to(EXAMPLES_DIR)
                out.write(r"\input{" + str(rel).replace("\\", "/") + "}\n")

        out.write("\n" + r"\end{document}" + "\n")

    print(f"✓ Created {master}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())